# Lokasyon akşam/gece oran kuralı
ENABLE_LOKASYON_AKSAM_GECE_ORAN_KURALI = CONFIG["ENABLE_LOKASYON_AKSAM_GECE_ORAN_KURALI"]
AKSAM_GECE_SHIFT_START_MIN = CONFIG["AKSAM_GECE_SHIFT_START_MIN"]
AKSAM_GECE_0000_DAHIL = CONFIG["AKSAM_GECE_0000_DAHIL"]
LOKASYON_AKSAM_GECE_ORANLARI = CONFIG["LOKASYON_AKSAM_GECE_ORANLARI"]
LOKASYON_AKSAM_GECE_ORAN_SAPMA_W = CONFIG["LOKASYON_AKSAM_GECE_ORAN_SAPMA_W"]
